---

- hosts: all
  sudo: true
  gather_facts: false
  vars:
    autologic_elasticsearch_configuration:
      cluster.name: "supercluster"
  roles:
    - autologic-python 
    - autologic-elasticsearch

  tasks:
    - name: Configure a virtual environment
      pip:
        requirements: "/development/requirements.txt"
        virtualenv: "/development/env"
        virtualenv_command: "/usr/local/bin/virtualenv"

    - name: Install global Python packages
      pip:
        name: "{{item}}"
        executable: "/usr/local/bin/pip"
      with_items:
        - "supervisor"
        # - "gunicorn"

    - name: Move our configuration up
      copy:
        src: "files/supervisord.conf"
        dest: "/etc/supervisord.conf"
        mode: 0644

    - name: Install our init script
      copy:
        src: "files/supervisord"
        dest: "/etc/init.d/supervisord"
        mode : 0775

    - name: Journal configuration directoru
      file:
        path: "/etc/journal"
        state: "directory"
        mode: 0755

    - name: Move our configuration in place 
      copy:
        src: "files/journal.yml"
        dest: "/etc/journal/"
        mode: 0644

    - name: Stop any existing Supervisord process
      service:
        name: "supervisord"
        state: "stopped"

    - name: Start Supervisord 
      service:
        name: "supervisord"
        state: "started"

    - name: Start Journal
      command: /usr/local/bin/supervisorctl restart journal 

    - name: Disable the default RHEL firewall
      service:
        name: "iptables"
        state: "stopped"
        enabled: false
