
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "movedx/centos-6.6"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../.", "/development"

  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
    ansible.extra_vars = {
      ansible_python_interpreter: '/usr/local/bin/python'
    }
  end

  config.vm.define "autologic-journal"
end
